name: dartterm
description: A basic Dart REPL in a Flutter UI.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  xterm: ^3.4.1
  async: ^2.10.0
  logging: ^1.1.1
  dart_eval: ^0.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: CascadiaMono
      fonts:
        - asset: fonts/CascadiaMonoPL.ttf
